# ============ Stage 1: Tools Installation ============
FROM golang:1.24 AS tools

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
      go install github.com/go-task/task/v3/cmd/task@v3.44.0 && \
      go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.29.0 && \
      go install github.com/a-h/templ/cmd/templ@v0.3.898 && \
      go install github.com/air-verse/air@v1.62.0 && \
      go install github.com/pressly/goose/v3/cmd/goose@v3.24.3 && \
      cp /go/bin/* /usr/local/bin/

# ============ Stage 2: Development Environment ============
FROM golang:1.24

WORKDIR /app

COPY --from=tools /usr/local/bin/ /usr/local/bin/

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

CMD ["air", "-c", ".air.toml"]